field.formatter.settings.date_range_without_time:
  type: field.formatter.settings.datetime_custom
  label: 'Date range (without time)'
  mapping:
    separator:
      type: string
      label: 'Separator'
    single:
      type: date_format
      label: 'Date format for single date'
    single_all_day:
      type: date_format
      label: 'Date format for the single date if the date is "all day"'
    one_day:
      type: date_format
      label: 'Date format for the single day date range'
    one_month:
      type: date_format
      label: 'Date format for the single month date range'
    several_months:
      type: date_format
      label: 'Date format for the single year date range'
    several_years:
      type: date_format
      label: 'Date format for multiple years date range'
