# Schema for the configuration files of the uc_paypal_plus module.
uc_paypal_plus.settings:
  type: config_object
  label: 'PayPal Plus settings'
  mapping:
    wpsplus_email:
      type: email
      label: 'PayPal Plus e-mail address'
    wppplus_server:
      type: string
      label: 'API server'
    apiplus_username:
      type: string
      label: 'API username'
    apiplus_password:
      type: string
      label: 'API password'
    apiplus_signature:
      type: string
      label: 'Signature'
    ecplus_landingpage_style:
      type: string
      label: 'Default PayPal Plus landing page'
    ecplus_rqconfirmed_addr:
      type: boolean
      label: 'Require PPP Express Checkout users to use a PayPal Plus confirmed shipping address'
    ecplus_review_shipping:
      type: boolean
      label: 'Enable the shipping select form on the Review payment page'
    ecplus_review_company:
      type: boolean
      label: 'Enable the company name box on the Review payment page'
    ecplus_review_phone:
      type: boolean
      label: 'Enable the contact phone number box on the Review payment page'
    ecplus_review_comment:
      type: boolean
      label: 'Enable the comment text box on the Review payment page'
    wppplus_cc_txn_type:
      type: string
      label: 'Payment action'

payment_method.settings.paypalplus_ec:
  type: mapping
  label: 'PayPal Plus settings'
  mapping:
    wpsplus_email:
      type: string
      label: 'PayPal Plus e-mail address'
    wppplus_server:
      type: uri
      label: 'API server'
    apiplus:
      type: mapping
      label: 'API settings'
      mapping:
        apiplus_username:
          type: string
          label: 'API username'
        apiplus_password:
          type: string
          label: 'API password'
        apiplus_signature:
          type: string
          label: 'Signature'
    ecplus_landingpage_style:
      type: string
      label: 'Default PayPal Plus landing page'
    ecplus_rqconfirmed_addr:
      type: boolean
      label: 'Require PPP Express Checkout users to use a PayPal Plus confirmed shipping address'
    ecplus_review_shipping:
      type: boolean
      label: 'Enable the shipping select form on the Review payment page'
    ecplus_review_company:
      type: boolean
      label: 'Enable the company name box on the Review payment page'
    ecplus_review_phone:
      type: boolean
      label: 'Enable the contact phone number box on the Review payment page'
    ecplus_review_comment:
      type: boolean
      label: 'Enable the comment text box on the Review payment page'
    wppplus_cc_txn_type:
      type: string
      label: 'Payment action'